#!/bin/bash

create-links() {
    # Set the users home directory
    USER_HOME=$(eval echo ~$SUDO_USER)

    # Assigning the cloned directory to the variable CLONED_DIR
    CLONED_DIR="$USER_HOME/conf-files"

    # Creating a symbolic link from cloned bin to the users bin directory
    ln -sf "$CLONED_DIR/bin" "$USER_HOME/bin"

    # # Creating a symbolic link from cloned config to the users config directory
    ln -sf "$CLONED_DIR/config" "$USER_HOME/.config"

    # # Creating a symbolic link from cloned bashrc to the users bashrc file
    ln -sf "$CLONED_DIR/home/bashrc" "$USER_HOME/.bashrc"
}